#!/usr/bin/env sh
set -eu

chmod +x speedtest

if [ ! -d bin ]; then
  mkdir bin
fi
if [ ! -d log ]; then
  mkdir log
fi

if [ ! -e 'bin/speedtest-cli' ]; then
  printf "\n%s\n" "downloading speedtest-cli..."
  wget -O bin/speedtest-cli https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py
  chmod +x bin/speedtest-cli
fi

if [ ! -e 'log/speedtest.log' ]; then
  bin/speedtest-cli --csv-header > 'log/speedtest.log'
  printf "\n%s\n" "log/speedtest.log created"
fi
