#!/usr/bin/env ruby
# frozen_string_literal: true

require 'csv'
require 'net/http'
require 'json'

require_relative 'lib/gchat'
require_relative 'lib/speedtest_log'

# This is a "test runner", designed to be called with 'Speedtest.run'.
class Speedtest
  class << self
    def run(speedtest_log)
      setup
      speedtest_log.run_speedtest
      speedtest_log.log_speedtest unless speedtest_log.results.empty?
      display_stats(speedtest_log)
      display_warnings(speedtest_log)
    end

    def display_stats(speedtest_log)
      puts speedtest_log.stats_printout(:local).join("\n")
    end

    def display_warnings(speedtest_log)
      varieties.each do |variety, threshold|
        average = speedtest_log.check_minimum variety, threshold
        msg = "Warning - #{variety} speed of #{average} Mb/sec is under the " \
              "minimum threshold of #{threshold}."

        unless average
          puts msg
          GChat.new.message(msg)
        end
      end
    end

    def setup
      @download_minimum = 40
      @upload_minimum = 40
    end

    def varieties
      { download: @download_minimum, upload: @upload_minimum }
    end
  end
end

stl = SpeedTestLog.new

if ARGV[0] == '--stats'
  puts stl.stats_printout(:logfile).join("\n")
  exit
end

Speedtest.run stl
